#!/bin/bash
echo "🚀 TRADINO LIVE TRADING SETUP"
echo "============================="
echo ""
echo "Für ECHTES Live-Trading setzen Sie:"
echo ""
echo "export BITGET_API_KEY='YOUR_REAL_BITGET_API_KEY'"
echo "export BITGET_SECRET='YOUR_REAL_BITGET_SECRET'"  
echo "export BITGET_PASSPHRASE='YOUR_REAL_BITGET_PASSPHRASE'"
echo ""
echo "Dann starten Sie:"
echo "python3 final_live_trading_system.py"
echo ""
echo "⚠️ DAS SYSTEM WIRD DANN MIT ECHTEM GELD HANDELN!"
