# =========================================================================
# TRADINO UNSCHLAGBAR - Prometheus Configuration
# Comprehensive monitoring for trading application and infrastructure
# =========================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'tradino-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # TRADINO Main Application
  - job_name: 'tradino-app'
    static_configs:
      - targets: ['tradino-app:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: tradino-app:8000

  # TRADINO Dashboard
  - job_name: 'tradino-dashboard'
    static_configs:
      - targets: ['tradino-app:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['tradino-redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL monitoring  
  - job_name: 'postgres'
    static_configs:
      - targets: ['tradino-postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['tradino-nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Custom Trading Metrics
  - job_name: 'tradino-trading-metrics'
    static_configs:
      - targets: ['tradino-app:8000']
    metrics_path: /api/metrics/trading
    scrape_interval: 10s
    params:
      format: ['prometheus']

  # Exchange API Health
  - job_name: 'exchange-health'
    static_configs:
      - targets: ['tradino-app:8000']
    metrics_path: /api/metrics/exchange
    scrape_interval: 30s

  # AI Model Performance
  - job_name: 'ai-model-metrics'
    static_configs:
      - targets: ['tradino-app:8000']
    metrics_path: /api/metrics/ai
    scrape_interval: 60s

  # Risk Management Metrics
  - job_name: 'risk-metrics'
    static_configs:
      - targets: ['tradino-app:8000']
    metrics_path: /api/metrics/risk
    scrape_interval: 30s

  # Performance Metrics
  - job_name: 'performance-metrics'
    static_configs:
      - targets: ['tradino-app:8000']
    metrics_path: /api/metrics/performance
    scrape_interval: 60s

  # Telegram Bot Metrics
  - job_name: 'telegram-bot'
    static_configs:
      - targets: ['tradino-app:8000']
    metrics_path: /api/metrics/telegram
    scrape_interval: 60s

  # Blackbox exporter for external endpoints
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.bitget.com/health
        - https://nobelbrett.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-storage.example.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read for historical data (optional)
# remote_read:
#   - url: "https://prometheus-remote-storage.example.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password" 